# Generated by Django 5.1 on 2024-12-31 23:58

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='unit_test',
            new_name='assignment_questions',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='has_unit_test',
            new_name='has_assignment',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='password',
        ),
        migrations.AddField(
            model_name='book',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='location',
            field=models.CharField(choices=[('library', 'Library'), ('book_store', 'Book store')], max_length=10),
        ),
        migrations.AlterField(
            model_name='class',
            name='category',
            field=models.CharField(choices=[('S', 'Secondary'), ('P', 'Primary')], max_length=24),
        ),
        migrations.AlterField(
            model_name='course',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='school.teacher'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='group_name',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student'), ('applicant', 'Applicant')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
