# Generated by Django 5.1 on 2025-01-01 00:09

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_rename_course_status_course_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='class',
            name='category',
            field=models.CharField(choices=[('S', 'Secondary'), ('P', 'Primary')], max_length=1),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='group_name',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('A', 'Admin'), ('T', 'Teacher'), ('S', 'Student'), ('A', 'Applicant')], max_length=1),
        ),
    ]
