# Generated by Django 5.1 on 2025-01-01 00:18

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_attendance_status_alter_class_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='group_name',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=128),
        ),
    ]
