# Generated by Django 5.1 on 2024-09-03 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_lesson_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='school.student'),
        ),
    ]
