# Generated by Django 5.1 on 2025-01-01 21:11

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_studygroup_group_name_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='group_name',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=128),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='_class',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_teacher', to='school.class'),
        ),
    ]
