# Generated by Django 5.1 on 2024-09-03 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_lesson_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='teacher',
        ),
    ]
