# Generated by Django 5.1 on 2024-09-06 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_assignment_classschedule_course_exam_module_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='assignment',
            name='questions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='lesson',
            name='estimated_time',
            field=models.SmallIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='school.module', null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='school.lesson'),
        ),
        migrations.AlterField(
            model_name='course',
            name='picture',
            field=models.CharField(max_length=64),
        ),
    ]
