# Generated by Django 5.1 on 2025-01-02 05:40

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_alter_studygroup_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='_class',
        ),
        migrations.AddField(
            model_name='teacher',
            name='form_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_teacher', to='school.class'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='group_name',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=128),
        ),
    ]
