# Generated by Django 5.1 on 2025-01-02 05:42

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_remove_teacher__class_teacher_form_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='group_name',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=128),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='form_class',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_teacher', to='school.class'),
        ),
    ]
