# Generated by Django 5.1 on 2024-09-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_alter_lesson_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='estimated_time',
            field=models.SmallIntegerField(default=None, null=True),
        ),
    ]
