# Generated by Django 5.1 on 2025-01-07 10:48

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_subject_term_remove_teacher_subjects_class_subjects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='subjects',
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='group_name',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=128),
        ),
    ]
