# Generated by Django 5.1 on 2025-01-07 10:49

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_remove_class_subjects_alter_studygroup_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='nick_name',
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='group_name',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=128),
        ),
    ]
