# Generated by Django 5.1 on 2025-01-14 12:12

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_alter_studygroup_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='student',
        ),
        migrations.RemoveField(
            model_name='unittest',
            name='module',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='obtainable_score',
            new_name='obtainable_mark',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='category',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='course',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='date',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='score',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='score',
            name='date_submitted',
        ),
        migrations.RemoveField(
            model_name='score',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='score',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.AddField(
            model_name='applicant',
            name='made_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='class_subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='school.classsubject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='date_posted',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='due_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='exam',
            name='time_allowed',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='score',
            name='date_posted',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='school.subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=6),
        ),
        migrations.AddField(
            model_name='term',
            name='year',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='score',
            name='score_type',
            field=models.CharField(choices=[('Assignment', 'Assignment'), ('Test', 'Test'), ('Exam', 'Exam')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='group_name',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=128),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.JSONField(default=list)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('obtainable_mark', models.IntegerField()),
                ('class_subject', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='school.classsubject')),
            ],
        ),
        migrations.RenameModel(
            old_name='ClassSubjectOutline',
            new_name='Outline',
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('outline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='school.outline')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_score', models.IntegerField(default=0)),
                ('test_score', models.IntegerField(default=0)),
                ('exam_score', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('grade', models.CharField(default=None, max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_sheets', to='school.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_sheets', to='school.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('overall_total', models.IntegerField(default=0)),
                ('overall_average', models.FloatField(default=0.0)),
                ('teacher_comment', models.CharField(default=None, max_length=120)),
                ('principal_comment', models.CharField(default=None, max_length=120)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='school.student')),
                ('score_sheets', models.ManyToManyField(related_name='report_cards', to='school.scoresheet')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.JSONField(default=list)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('obtainable_mark', models.IntegerField()),
                ('class_subject', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='school.classsubject')),
            ],
        ),
        migrations.DeleteModel(
            name='ClassOutlineNote',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='UnitTest',
        ),
    ]
