# Generated by Django 5.1 on 2025-01-15 21:52

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_remove_grade_student_remove_unittest_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='time_allowed',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='test',
            name='time_allowed',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='obtainable_mark',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='exam',
            name='obtainable_mark',
            field=models.IntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='exam',
            name='time_allowed',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='group_name',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=128),
        ),
        migrations.AlterField(
            model_name='test',
            name='obtainable_mark',
            field=models.IntegerField(default=20),
        ),
    ]
