# Generated by Django 5.1 on 2024-09-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_alter_module_estimated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='estimated_time',
            field=models.SmallIntegerField(default=None),
        ),
    ]
