# Generated by Django 5.1 on 2025-01-17 09:49

import django.db.models.deletion
import shortuuid.main
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_assignment_time_allowed_test_time_allowed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='group',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='contact_mail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='made_payment',
            new_name='has_made_payment',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='parent_contact_mail',
            new_name='parent_email',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='contact_phone',
            new_name='parent_phone_number',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='parent_contact_phone',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sent_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='applicant',
            name='d_o_b',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='d_o_b',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='due_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='school.term'),
        ),
        migrations.AlterField(
            model_name='test',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group_name', models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to='school.student')),
                ('members', models.ManyToManyField(blank=True, related_name='study_groups', to='school.student')),
                ('students_online', models.ManyToManyField(blank=True, related_name='online_in_groups', to='school.student')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='school.group')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TuitionFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField()),
                ('paid', models.FloatField(default=0.0)),
                ('has_made_full_payment', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tuition_fees', to='school.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tuition_fees', to='school.term')),
            ],
        ),
        migrations.DeleteModel(
            name='StudyGroup',
        ),
    ]
