# Generated by Django 5.1 on 2025-01-17 09:50

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_remove_message_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='d_o_b',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='d_o_b',
            field=models.DateField(default=None, null=True),
        ),
    ]
