# Generated by Django 5.1 on 2024-09-08 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_alter_lesson_module_alter_module_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='type',
            new_name='score_type',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='day',
        ),
        migrations.AddField(
            model_name='classschedule',
            name='lesson',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='score',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_scores', to='school.course'),
        ),
        migrations.AddField(
            model_name='score',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_scores', to='school.exam'),
        ),
        migrations.AddField(
            model_name='score',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_scores', to='school.lesson'),
        ),
        migrations.AlterField(
            model_name='score',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='school.student'),
        ),
    ]
