# Generated by Django 5.1 on 2025-01-17 09:53

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_alter_applicant_d_o_b_alter_group_group_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='d_o_b',
        ),
        migrations.RemoveField(
            model_name='student',
            name='d_o_b',
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=128),
        ),
    ]
