# Generated by Django 5.1 on 2025-01-17 09:58

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_remove_applicant_d_o_b_remove_student_d_o_b_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='email',
            new_name='contact_mail',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='parent_phone_number',
            new_name='contact_phone',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='parent_email',
            new_name='parent_contact_mail',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='phone_number',
            new_name='parent_contact_phone',
        ),
        migrations.AddField(
            model_name='applicant',
            name='d_o_b',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='d_o_b',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=128),
        ),
    ]
