# Generated by Django 5.1 on 2024-09-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_alter_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('W', 'Waitlisted')], default='O', max_length=1),
        ),
    ]
