# Generated by Django 5.1 on 2024-09-10 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0024_course_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='status',
            new_name='course_status',
        ),
    ]
