# Generated by Django 5.1 on 2024-09-13 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_rename_status_course_course_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('due_date', models.DateField()),
                ('due_time', models.TimeField()),
                ('obtainable_mark', models.IntegerField()),
                ('tota_obtainable_mark', models.IntegerField()),
                ('questions', models.JSONField(default=list)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='school.module')),
            ],
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
