# Generated by Django 5.1 on 2025-01-17 18:17

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_rename_contact_mail_applicant_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entranceexamscore',
            name='applicant_id',
        ),
        migrations.AddField(
            model_name='entranceexamscore',
            name='applicant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='score', to='school.applicant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=128),
        ),
    ]
