# Generated by Django 5.1 on 2024-10-03 06:02

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0028_alter_studygroup_group_name_payment_studentpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='group_name',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('type', '_class')},
        ),
    ]
