# Generated by Django 5.1 on 2024-10-05 10:38

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0030_alter_studygroup_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpayment',
            name='history',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='group_name',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=128),
        ),
    ]
