from .applicant_views import *
from .attendance_views import *
from .book_views import *
from .class_views import *
from .course_views import *
from .entrance_exam_views import *
from .lesson_views import *
from .module_views import *
from .parent_views import *
from .payment_views import *
from .score_views import *
from .student_views import *
from .study_group_views import *
from .teacher_views import *
from .exam_views import *
from .schedule_views import *
from .auth_views import *
from .subject_views import *
from .term_views import *
from .notification_views import *