from django.urls import path
from .views import *


urlpatterns = [
    path('api/v1/auth', CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/v1/auth/refresh', CustomTokenRefreshView.as_view(), name='token_refresh'),
    path('api/v1/notifications', NotificationListView.as_view(), name='notifications'),
    path('api/v1/subjects', SubjectList.as_view(), name='subjects'),
    path('api/v1/outlines', OutlineList.as_view(), name='outlines'),
    path('api/v1/outlines/<int:pk>', OutlineDetail.as_view(), name='outline'),
    path('api/v1/notes', NoteList.as_view(), name='notes'),
    path('api/v1/notes/<int:pk>', NoteDetail.as_view(), name='note'),
    path('api/v1/assignments', AssignmentList.as_view(), name='assignments'),
    path('api/v1/assignments/<int:pk>', AssignmentDetail.as_view(), name='assignment'),
    path('api/v1/tests', TestList.as_view(), name='tests'),
    path('api/v1/tests/<int:pk>', TestDetail.as_view(), name='test'),
    path('api/v1/exams', ExamList.as_view(), name='exams'),
    path('api/v1/exams/<int:pk>', ExamDetail.as_view(), name='exam'),
    path('api/v1/terms', CreateTerm.as_view(), name='terms'),
    path('api/v1/terms/<int:pk>', RetrieveTerm.as_view(), name='term'),
    path('api/v1/applicants', ApplicantList.as_view(), name='applicant-list'),
    path('api/v1/applicants/<int:pk>', ApplicantDetail.as_view(), name='applicant-detail'),
    path("api/v1/students", StudentList.as_view(), name="student-list"),
    path("api/v1/students/<int:pk>", StudentDetail.as_view(), name="student-detail"),
    path("api/v1/classes", ClassList.as_view(), name="class-list"),
    path("api/v1/classes/<int:pk>", ClassDetail.as_view(), name="class-detail"),
    path("api/v1/teachers", TeacherList.as_view(), name="teacher-list"),
    path("api/v1/teachers/<int:pk>", TeacherDetail.as_view(), name="teacher-detail"),
    path("api/v1/scores", ScoreList.as_view(), name="scores"),
    path("api/v1/score", ScoreDetail.as_view(), name="score"),
    path("api/v1/score-sheets", ScoreSheetList.as_view(), name="score-sheets"),
    path("api/v1/report-cards", ReportCardList.as_view(), name="report-cards"),
    path("api/v1/report-card", ReportCardDetail.as_view(), name="report-card"),
    # path('api/v1/std_payment/<int:class_id>/<str:type>', StudentPaymentList.as_view(), name='std_payment'),
    # path('api/v1/std-payment/<int:pk>/<str:action>', StudentPaymentDetail.as_view(), name='std_payment'),
    # path('api/v1/payment/', PaymentList.as_view(), name='payment'),
    # path('api/v1/payment/<int:class_id>', PaymentList.as_view(), name='payment'),
    # path('api/v1/courses', CourseList.as_view(), name='course'), 
    path('api/v1/courses/<int:pk>', CourseDetail.as_view(), name='course-detail'), 
    path('api/v1/modules', ModuleList.as_view(), name='module'), 
    path('api/v1/modules/<int:pk>', ModuleList.as_view(), name='module-detail'), 
    path('api/v1/groups', StudyGroupList.as_view(), name='groups'),
    path('api/v1/groups/<int:pk>/<int:student_id>', StudyGroupDetail.as_view(), name='groups'),
    path('api/v1/groups/<int:group_id>/<str:data_type>', StudyGroupInfoList.as_view(), name='groups'),
    path('api/v1/entrance-exam-questions', EntranceExamQuestionList.as_view(), name='entrance-exam-questions'),
    path('api/v1/entrance-exam-score', EntranceExamScoreList.as_view(), name='entrance-exam-score'),
    path('api/v1/entrance-exam-score/<str:applicant_id>', EntranceExamScoreDetail.as_view(), name='entrance-exam-score'),
    path('api/v1/questions/', QuestionList.as_view(), name='question-list'),
    path('api/v1/questions/<int:pk>/', QuestionDetail.as_view(), name='question-detail'),
    path("api/v1/parents/", ParentList.as_view(), name="parent-list"),
    path("api/v1/parents/<int:pk>/", ParentDetail.as_view(), name="parent-detail"),
    path("api/v1/lessons/", LessonList.as_view(), name="lesson-list"),
    path("api/v1/lessons/<int:pk>/", LessonDetail.as_view(), name="lesson-detail"),
    path("api/v1/attendances/", AttendanceList.as_view(), name="attendance-list"),
    path("api/v1/attendances/<int:pk>/", AttendanceDetail.as_view(), name="attendance-detail"),
    path("api/v1/books/", BookList.as_view(), name="book-list"),
    path("api/v1/books/<int:pk>/", BookDetail.as_view(), name="book-detail"),
    path("api/v1/book_sales/", BookSaleList.as_view(), name="book_sale-list"),
    path("api/v1/book_sales/<int:pk>/", BookSaleDetail.as_view(), name="book_sale-detail"),
    path("api/v1/book_purchases/", BookPurchaseList.as_view(), name="book_purchase-list"),
    path(
        "api/v1/book_purchases/<int:pk>/",
        BookPurchaseDetail.as_view(),
        name="book_purchase-detail",
    ),
    path("api/v1/checkouts/", CheckoutList.as_view(), name="checkout-list"),
    path("api/v1/checkouts/<int:pk>/", CheckoutDetail.as_view(), name="checkout-detail"),
]
